sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=braidneb/libme-config
  - docker build -t $CONFIG ./config
  - docker tag -f $CONFIG $CONFIG:$TAG
  - docker push $CONFIG