sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=braidneb/libme-config
  - docker build -t $CONFIG ./config
  - docker tag -f $CONFIG $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY SERVICE
  - export REGISTRY=braidneb/libme-registry
  - docker build -t $REGISTRY ./registry
  - docker tag -f $REGISTRY $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY SERVICE
  - export GATEWAY=braidneb/libme-gateway
  - docker build -t $GATEWAY ./gateway
  - docker tag -f $GATEWAY $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH=braidneb/libme-auth
  - docker build -t $AUTH ./auth
  - docker tag -f $AUTH $AUTH:$TAG
  - docker push $AUTH

  # CONTENT SERVICE
  - export CONTENT=braidneb/libme-content
  - docker build -t $CONTENT ./content
  - docker tag -f $CONTENT $CONTENT:$TAG
  - docker push $CONTENT