logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${registry.hostname:registry}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${auth-service.hostname:auth}:5000/auth/users/current

spring:
  rabbitmq:
    host: rabbitmq