logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DEBUG_HOSTNAME:registry}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${DEBUG_HOSTNAME:auth}:5000/auth/users/current

spring:
  rabbitmq:
    host: ${DEBUG_HOSTNAME:rabbitmq}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region: eu-west-1