hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  prefix: /api
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /auth/**
        url: http://localhost:5000
        sensitiveHeaders: FuckingHackForZUULfilterCouseHeDropsAuthHeader
        stripPrefix: false

    content-service:
        path: /content/**
        serviceId: content-service
        sensitiveHeaders: FuckingHackForZUULfilterCouseHeDropsAuthHeader
        stripPrefix: false

    torrent-service:
        path: /torrent/**
        serviceId: torrent-service
        stripPrefix: false

server:
  port: 4000