hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /api/auth/**
        url: http://${DEBUG_HOSTNAME:auth}:5000
        stripPrefix: false

    content-service:
        path: /api/content/**
        serviceId: content-service
        stripPrefix: false

    notification-service:
        path: /api/torrent/**
        serviceId: torrent-service
        stripPrefix: false

server:
  port: 4000