security:
  oauth2:
    client:
      clientId: torrent-service
      clientSecret: ${TORRENT_SERVICE_PASSWORD}
      accessTokenUri: http://{DEBUG_HOSTNAME:auth}:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ds047085.mongolab.com
      username: admin
      password: 1q2w3e
      database: lib_me
      port: 47085

server:
  context-path: /torrent
  port: 7000
torrent:
  downloads:
    folder: c:/downloads